services:
  games-app:
    build: .
    image: do-ob-games
    container_name: do-ob-games-container
    restart: unless-stopped
    ports:
      - "5500:5500"
    volumes:
      - ./analytics.db:/app/analytics.db